name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

# default permission at repo level should be read-only
# be deliberate and precise in ensuring least privilege
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
